parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 12
  project: tsconfig.json
  sourceType: module

plugins:
  - '@typescript-eslint/eslint-plugin'
  - simple-import-sort

extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'

root: true

env:
  node: true
  es2020: true

rules:
  arrow-parens:
    - error
    - as-needed
  curly:
    - error
    - multi-line
  import/no-cycle: off
  no-extend-native: error
  no-unused-vars: off
  simple-import-sort/exports: error
  simple-import-sort/imports: error
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/naming-convention':
    - error
    - selector: interface
      format: [PascalCase]
      prefix: [I]
    - selector: enum
      format: [PascalCase]
      prefix: [CE_]
  '@typescript-eslint/no-explicit-any': error
  '@typescript-eslint/no-duplicate-enum-values': error
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/prefer-as-const': error
