server:
  hostname: 127.0.0.1
  port: 9000
  trustProxy:
    - loopback
service:
  database:
    type: mariadb
    host: 127.0.0.1
    port: 3306
    username: tywzoj
    password: tywzoj
    database: tywzoj
  redis: redis://127.0.0.1:6379
  mail:
    address: tywzoj@mail.tywzoj.top
    transport: smtp://username:password@smtp.tywzoj.top:25
  minio:
    endPoint: minio.tywzoj.top
    port: 9000
    useSSL: true
    accessKey: accesskey
    secretKey: secretkey
    bucket: tywzoj
    userEndPointUrl: # example: https://user.minio.tywzoj.top
    judgeEndPointUrl:
security:
  crossOrigin:
    enabled: true
    whitelist: # whitelist is an array and each item must be an url with protocol
      - http://tywzoj.top
      - https://tywzoj.top
  sessionSecret: don't leak this
  recaptcha:
    secretKey:
    useRecaptchaNet: false
    proxyUrl:
  rateLimit:
    enabled: false
    maxRequests: 200
    durationSeconds: 10
    whitelist: # whitelist is an array and each item must be a CIDR
      - 127.0.0.0/8
resourceLimit:
  problemTestdataFiles: 40
  problemTestdataSize: 134217728
  problemAdditionalFileFiles: 40
  problemAdditionalFileSize: 134217728
  problemSamplesToRun: 10
  problemTestcases: 20
  problemTimeLimit: 5000
  problemMemoryLimit: 2048
  submissionFileSize: 10485760
queryLimit:
  problem: 100
  problemSet: 30
  submission: 10
  submissionStatistic: 10
  homework: 30
  contest: 30
  article: 50
  articleReply: 50
  searchUser: 20
  searchGroup: 20
  userList: 100
preference:
  siteName: TYWZOJ
  domainIcpRecordInformation:
  security:
    recaptchaEnabled: false
    recaptchaKey:
    useRecaptchaNet: false
    requireEmailVerification: false
  pagination:
    homepageNotice: 10
    homepageUserList: 20
    homepageContest: 5
    homepageHomework: 5
    problem: 100
    problemSet: 30
    submission: 10
    submissionStatistic: 10
    homework: 30
    contest: 30
    article: 50
    articleReply: 50
    searchUser: 20
    searchGroup: 20
    userList: 100
  misc:
    gravatarCdn: https://cn.gravatar.com/avatar/
    sortUserBy: rating # sortUserBy can only be 'id', 'rating' or 'acceptedProblemCount'
    renderMarkdownInUserBio: true
    renderMarkdownInUserListBio: false


